# Generated by Django 4.2.2 on 2023-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0002_habilidades_alter_empleado_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="Habilidades",
            field=models.ManyToManyField(to="persona.habilidades"),
        ),
        migrations.AddField(
            model_name="empleado",
            name="avatar",
            field=models.ImageField(null=True, upload_to="empleado"),
        ),
    ]
