# Generated by Django 4.2.2 on 2023-06-18 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0003_empleado_habilidades_empleado_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(max_length=50, verbose_name="Cargo")),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos de los empleados",
            },
        ),
        migrations.AlterField(
            model_name="empleado",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="persona.cargos"
            ),
        ),
    ]
