# Generated by Django 4.2.2 on 2023-06-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0004_cargos_alter_empleado_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="empleado"),
        ),
    ]
