# Generated by Django 4.2.2 on 2023-06-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0006_rename_job_empleado_cargo"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Nombre completo"
            ),
        ),
    ]
