# Generated by Django 4.2.2 on 2023-06-29 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0008_alter_empleado_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="persona.cargos",
            ),
        ),
    ]
